# 创建 food 数据库，如果数据库存在则删除
drop database if exists food;
create database food;

# 使用数据库
use food;

# 根据 beers.json 生成创建 mysql 表的 sql 语句
create table beers (
    id int primary key auto_increment,
    name varchar(255),
    tagline varchar(255),
    first_brewed varchar(255),
    description text,
    image_url varchar(255),
    price float,
    abv float,
    ibu float,
    target_fg float,
    target_og float,
    ebc float,
    srm float,
    ph float,
    attenuation_level float,
    volume json,
    boil_volume json,
    method json,
    ingredients json,
    food_pairing json,
    brewers_tips text,
    contributed_by varchar(255)
);

# 根据 beers.json 生成插入 mysql 表的 sql 语句
INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Buzz', 'A Real Bitter Experience.', '09/2007', 'A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.', 'https://images.punkapi.com/v2/keg.png', '2.5', '4.5', '60', '1010', '1044', '20', '10', '4.4', '75', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Spicy chicken tikka masala", "Grilled chicken quesadilla", "Caramel toffee cake"]', 'The earthy and floral aromas from the hops can be overpowering. Drop a little Cascade in at the end of the boil to lift the profile with a bit of citrus.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Trashy Blonde', 'You Know You Shouldn''t', '04/2008', 'A titillating, neurotic, peroxide punk of a Pale Ale. Combining attitude, style, substance, and a little bit of low self esteem for good measure; what would your mother say?', 'https://images.punkapi.com/v2/2.png', '2.5', '4.1', '41.5', '1010', '1041.7', '15', '15', '4.4', '76', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Fresh crab with lemon", "Garlic butter dipping sauce", "Goats cheese salad", "Creamy lemon bar doused in powdered sugar"]', 'If you were feeling extra naughty you could try adding some oak chips to the fermenting beer. Be careful though, they can quickly overpower the beer.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Berliner Weisse With Yuzu - B-Sides', 'Japanese Citrus Berliner Weisse.', '11/2015', 'Japanese citrus fruit intensifies the sour nature of this German classic.', 'https://images.punkapi.com/v2/keg.png', '2.5', '4.2', '8', '1007', '1040', '8', '4', '3.2', '75', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Smoked chicken wings", "Miso ramen", "Yuzu cheesecake"]', 'Clean everything twice. All you want is the clean sourness of lactobacillus.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Pilsen Lager', 'Unleash the Yeast Series.', '09/2013', 'Our Unleash the Yeast series documents our experiments to showcase the epic potential of our favourite ingredient. In this edition we''re working with a traditional German lager yeast that offers up light, biscuity notes and a clean, dry finish.', 'https://images.punkapi.com/v2/keg.png', '2.5', '6.3', '55', '1012', '1060', '30', '15', '4.4', '80', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Spicy crab cakes", "Spicy cucumber and carrot Thai salad", "Sweet filled dumplings"]', 'Ferment at higher or lower temperatures to select the esters that will create clove- like or banana-like flavours.', 'Ali Skinner <AliSkinner>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Avery Brown Dredge', 'Bloggers'' Imperial Pilsner.', '02/2011', 'A German Imperial Pilsner, dry-hopped with as much punch as our brewers could muster. Assertive, sharp, fruity and grassy.', 'https://images.punkapi.com/v2/keg.png', '2.5', '7.2', '59', '1010', '1069', '15', '7.5', '4.4', '87', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Vietnamese squid salad", "Chargrilled corn on the cob with paprika butter", "Strawberry and rhubarb pie"]', 'Make sure you have a big enough yeast starter to ferment through the OG and lager successfully.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Electric India', 'Vibrant Hoppy Saison.', '05/2013', 'Electric India is a hoppy saison brewed with mango and spices – a collaboration with DJ Sinden.', 'https://images.punkapi.com/v2/keg.png', '2.5', '5.2', '38', '1007', '1047', '30', '15', '4.4', '75', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Lamb ragu", "Smoked duck Caesar salad", "Ginger spice cookies"]', 'Brettanomyces bruxellensis trois adds a twist to the funk, creating a spicy, fruity kick. Keep an eye on it, it can go too far, too fast.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('AB:12', 'Imperial Black Belgian Ale.', '07/2012', 'Belgian Imperial Stout brewed with copious amounts of dark malts, pure cacao and coffee, balanced by the subtle addition of naga chilli. Perfect for ageing in your cellar or drinking fresh if you are lucky enough to get your paws on some.', 'https://images.punkapi.com/v2/12.png', '2.5', '11.2', '35', '1014', '1108', '180', '90', '5.6', '81', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Spicy chicken skewers", "Pan seared steak", "Chocolate cake"]', 'The chili heat fades with age. Best stored cool.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Fake Lager', 'Bohemian Pilsner.', '03/2013', 'A full bodied, decadently smooth coffee beer in collaboration with local roaster Dark Woods. 7 different malts combine with 7 different coffees added at 3 different points during the brew to create a sweet toffee, rich fruit and chocolate depth, accented with notes of vanilla, and hazelnut. A coffee beer designed with texture, aroma and deliciousness in mind, brewed to celebrate locality and a shared philosophy in creative quality.', 'https://images.punkapi.com/v2/keg.png', '2.5', '4.7', '40', '1012', '1047', '12', '6', '4.4', '75', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Vietnamese noodle salad", "Chicken tikka masala", "Buttermilk pancakes"]', 'Mash in at a higher temperature to leave more unfermentable sugars in the wort. This gives the beer a sweeter base to compliment the coffee flavours.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('AB:07', 'Whisky Cask-Aged Scotch Ale.', '03/2011', 'Scotch Ales are inherently sweet beers, and we’ve added to the rich malt profile by ageing the beer in freshly emptied 21 year-old Speyside whisky casks. We sourced the casks from the Glenfiddich distillery in Dufftown, who have been kind enough to send them to us after filling them with their whisky. The result is an incredibly complex beer, deep chestnut in colour with a tanned leather aroma that comes from the whisky soaked wooden walls of the cask.', 'https://images.punkapi.com/v2/7.png', '2.5', '12.5', '30', '1020', '1106', '84', '42', '5.6', '80', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Kedgeree", "Scotch broth", "Cranachan"]', 'Be careful not to leave behind any of the residual yeast when bottling. Add sugar to the cold liquor before you bottle to ensure even carbonation.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Rabiator', 'Imperial Wheat Beer', '03/2011', 'Imperial Wheat beer / Weizenbock brewed by a homesick German in leather trousers. Think banana bread, bubble gum and David Hasselhoff.', 'https://images.punkapi.com/v2/keg.png', '2.5', '10.27', '26', '1014', '1090', '30', '15', '4.4', '84', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Grilled sausages", "Sweet potato fries", "Vanilla ice cream with chocolate sauce"]', 'Weizen yeast gives characteristic flavours of banana, clove and vanilla. Once fermentation is complete we add a lager yeast which increases the crispness of the beer.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Vice Bier', 'Hoppy Wheat Bier.', '04/2013', 'Brewed in collaboration with New York''s Other Half this is a wheat beer amplified to imperial potency with Amarillo, Citra, Columbus, Cascade & Centennial hops. Expect masses of tangerine flavour and aroma with a rounded bitterness.', 'https://images.punkapi.com/v2/keg.png', '2.5', '4.1', '50', '1010', '1043', '15', '21.5', '4.4', '75', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Vietnamese squid salad", "Chargrilled corn on the cob with paprika butter", "Strawberry and rhubarb pie"]', 'Mash in at a higher temperature to leave more unfermentable sugars in the wort. This gives the beer a sweeter base to compliment the hoppy flavours.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Devine Rebel (w/ Mikkeller)', 'Oak-aged Barley Wine.', '12/2008', 'Aged in Speyside whisky casks, our own Devine Rebel is a collision of worlds. Flavours of toffee, caramel and Demerara fuse with vanilla, smoke and chocolate.', 'https://images.punkapi.com/v2/keg.png', '2.5', '12.5', '100', '1020', '1108', '180', '90', '5.6', '81', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Stilton on gingerbread biscuits", "Pot roasted artichokes", "Lamb chops with caramelised figs"]', 'Mash in at a higher temperature to leave more unfermentable sugars in the wort. This gives the beer a sweeter base to compliment the hoppy flavours.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Storm', 'Islay Whisky Aged IPA.', '12/2007', 'Storm is a brew that rages against the elements. A tempestuous IPA brewed with our rampaging hoppy friends from near the Arctic Circle, Nogne. This storm of hops and spicy rye malt will leave you battered, bruised and begging for more.', 'https://images.punkapi.com/v2/keg.png', '2.5', '8', '60', '1010', '1068', '30', '15', '4.4', '88', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Spicy chicken skewers", "Fish tacos with hot sauce", "Lemon pound cake with a ice sugar glaze"]', 'The earthy and floral aromas from the hops can be overpowering. Drop a little Cascade in at the end of the boil to lift the profile with a bit of citrus.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('The End Of History', 'The World''s Strongest Beer.', '06/2011', 'This blond Belgian ale is infused with nettles from the Scottish Highlands and Fresh juniper berries. Only 12 bottles have been made and each comes with its own certificate and is presented in a stuffed stoat or grey squirrel. The striking packaging was created by a very talented taxidermist and all the animals used were road kill. This release is a limited run of 11 bottles, 7 stoats and 4 grey squirrels. Each ones comes with its own certificate of authenticity.', 'https://images.punkapi.com/v2/keg.png', '2.5', '55', '0', '1000', '1112', '10', '85', '4.4', '100', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Candy floss", "Piña colada", "Toast with marmalade"]', 'The irony of existentialism, the parody of being and the inherent contradictions of post-modernism, all so delicately conveyed by the blocky, yet sharp finish.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Bad Pixie', 'Spiced Wheat Beer.', '04/2008', '2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.', 'https://images.punkapi.com/v2/keg.png', '2.5', '4.7', '45', '1010', '1047', '8', '4', '3.2', '79', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Poached sole fillet with capers", "Summer fruit salad", "Banana split"]', 'Juniper berries are used to flavour gin. The ripe berries, when dried and crushed, deliver a sweet, spicy and aromatic freshness.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Skull Candy', 'Pacific Hopped Amber Bitter.', '04/2010', 'A 4.7% amber beer with a rocky white head and a whole lot of hops from the Pacific Northwest of America.', 'https://images.punkapi.com/v2/keg.png', '2.5', '3.5', '33', '1012', '1043', '30', '15', '4.4', '75', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Fresh crab with lemon", "Garlic butter dipping sauce", "Goats cheese salad", "Creamy lemon bar doused in powdered sugar"]', 'The earthy and floral aromas from the hops can be overpowering. Drop a little Cascade in at the end of the boil to lift the profile with a bit of citrus.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Dog B', 'Cacao, Coffee Chili Anniversary Stout.', '09/2013', 'Dog B is a 15.1% imperial stout brewed with copious amounts of dark malts, pure cacao, coffee beans and chili. Bourbon barrel ageing adds notes of vanilla and oak, and the result is a stunningly complex and rewarding beer.', 'https://images.punkapi.com/v2/keg.png', '2.5', '15.1', '85', '1030', '1150', '180', '80', '4.4', '100', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Chocolate cake", "Vanilla ice cream", "Chilli con carne"]', 'Brewed to celebrate our anniversary. Mix together equal measures of imperial stout and Dog A. Add a hefty dose of cacao nibs, coffee and chilli.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Hello My Name Is Mette-Marit', 'Lingonberry Double IPA.', '03/2013', 'A Double IPA with cloudberries added to the conditioning tank. Lingonberry is a Scandinavian berry, similar in bitterness to cranberries.', 'https://images.punkapi.com/v2/keg.png', '2.5', '8.2', '70', '1010', '1080', '30', '15', '4.4', '87', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Fried elk steak with blackened edges", "Lingonberry jam with a hint of cinnamon", "Swedish pancakes with lingonberries"]', 'The lingonberries are added to the conditioning tank. This beer is inspired by the Danish beer, Mørke, by Mikkeller.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Hello My Name Is Beastie', 'Smoked Porter.', '03/2013', 'A powerful, warming, imperial porter brewed with German, English, Belgian and smoked malts. Its seductive palate of chocolate, coffee and smoke is generously spiked with hops and a lingering, bitter finish.', 'https://images.punkapi.com/v2/keg.png', '2.5', '8.2', '70', '1010', '1080', '30', '15', '4.4', '87', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Fried elk steak with blackened edges", "Lingonberry jam with a hint of cinnamon", "Swedish pancakes with lingonberries"]', 'The lingonberries are added to the conditioning tank. This beer is inspired by the Danish beer, Mørke, by Mikkeller.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Hello My Name Is Sonja', 'Juniper Double IPA.', '03/2013', 'A Double IPA with cloudberries added to the conditioning tank. Lingonberry is a Scandinavian berry, similar in bitterness to cranberries.', 'https://images.punkapi.com/v2/keg.png', '2.5', '8.2', '70', '1010', '1080', '30', '15', '4.4', '87', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Fried elk steak with blackened edges", "Lingonberry jam with a hint of cinnamon", "Swedish pancakes with lingonberries"]', 'The lingonberries are added to the conditioning tank. This beer is inspired by the Danish beer, Mørke, by Mikkeller.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Hello My Name Is Vladimir', 'Lingonberry Double IPA.', '03/2013', 'A Double IPA with cloudberries added to the conditioning tank. Lingonberry is a Scandinavian berry, similar in bitterness to cranberries.', 'https://images.punkapi.com/v2/keg.png', '2.5', '8.2', '70', '1010', '1080', '30', '15', '4.4', '87', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Fried elk steak with blackened edges", "Lingonberry jam with a hint of cinnamon", "Swedish pancakes with lingonberries"]', 'The lingonberries are added to the conditioning tank. This beer is inspired by the Danish beer, Mørke, by Mikkeller.', 'Sam Mason <samjbmason>');

INSERT INTO beers (name, tagline, first_brewed, description, image_url, price, abv, ibu, target_fg, target_og, ebc, srm, ph, attenuation_level, volume, boil_volume, food_pairing, brewers_tips, contributed_by) VALUES ('Hello My Name Is Zé', 'Lingonberry Double IPA.', '03/2013', 'A Double IPA with cloudberries added to the conditioning tank. Lingonberry is a Scandinavian berry, similar in bitterness to cranberries.', 'https://images.punkapi.com/v2/keg.png', '2.5', '8.2', '70', '1010', '1080', '30', '15', '4.4', '87', '{"value": 20, "unit": "litres"}', '{"value": 25, "unit": "litres"}', '["Fried elk steak with blackened edges", "Lingonberry jam with a hint of cinnamon", "Swedish pancakes with lingonberries"]', 'The lingonberries are added to the conditioning tank. This beer is inspired by the Danish beer, Mørke, by Mikkeller.', 'Sam Mason <samjbmason>');

